apiVersion: v1
kind: Service
metadata:
  name: improvement-plan-service
  namespace: credit-coach
spec:
  selector:
    app: improvement-plan-service
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP
