apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score-service
  labels:
    app: credit-score-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: credit-score-service
  template:
    metadata:
      labels:
        app: credit-score-service
    spec:
      containers:
        - name: credit-score-service
          image: europe-west2-docker.pkg.dev/lloyds-credit-coach/services/credit-score-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: scores-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scores-db-credentials
                  key: password
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: credit-score-config
                  key: redis-host
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
